version: "3.9"
services:
    sftp:
        image: atmoz/sftp
        volumes:
            - report-data:/home/foo/upload
        ports:
            - "2222:22"
        command: foo:pass:${UID}:${GID}
    sftp_chown:
        image: atmoz/sftp
        volumes:
            - report-data:/home/foo/upload
        command: chown -R ${UID}:${GID} /home/foo/upload
        depends_on:
            - sftp
volumes:
    report-data:
